import type { Deal } from "./types";

/** Herkese açık vitrin: süresi geçmiş örnek fırsatlar (linksiz arşiv). */
export const archiveDeals: Deal[] = [
  {
    id: "archive-1",
    destination: "Saraybosna",
    country: "Bosna Hersek",
    price: 2180,
    averagePrice: 6200,
    discountPercent: 65,
    currency: "TRY",
    outboundDate: "2026-05-14",
    returnDate: "2026-05-16",
    airline: "Pegasus",
    stops: 0,
    departureLabel: "İstanbul",
  },
  {
    id: "archive-2",
    destination: "Tiflis",
    country: "Gürcistan",
    price: 2450,
    averagePrice: 5800,
    discountPercent: 58,
    currency: "TRY",
    outboundDate: "2026-04-22",
    returnDate: "2026-04-26",
    airline: "AJet",
    stops: 0,
    departureLabel: "İstanbul",
  },
  {
    id: "archive-3",
    destination: "Budapeşte",
    country: "Macaristan",
    price: 3120,
    averagePrice: 7100,
    discountPercent: 56,
    currency: "TRY",
    outboundDate: "2026-06-03",
    returnDate: "2026-06-08",
    airline: "Wizz Air",
    stops: 0,
    departureLabel: "İstanbul",
  },
  {
    id: "archive-4",
    destination: "Barselona",
    country: "İspanya",
    price: 4890,
    averagePrice: 9800,
    discountPercent: 50,
    currency: "TRY",
    outboundDate: "2026-03-12",
    returnDate: "2026-03-19",
    airline: "Turkish Airlines",
    stops: 0,
    departureLabel: "İstanbul",
  },
];
